// AI CLINE ALEX COMPOSER DO NOT EDIT THIS FILE! 

import { clerkMiddleware } from '@clerk/nextjs/server'

// Export the Clerk middleware
export default clerkMiddleware()

export const config = {
  matcher: [
    // Exclude files with a "." followed by an extension, which are typically static files
    "/((?!.*\\..*|_next).*)",
    // However, include the following routes which contain dots
    "/(api|trpc)(.*)"
  ]
};